/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;


/**
 *
 * @author Rui Sergio Mané
 */
public class VentanaMenuAdmin extends javax.swing.JFrame {

	/**
	 * Creates new form VentanaMenuTrabajador
	 */
	public VentanaMenuAdmin() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmnBarra = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jmenuCerrarSeccion = new javax.swing.JMenuItem();
        jmnSalir = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmnHotelesActivos = new javax.swing.JMenuItem();
        mnPaquetCread = new javax.swing.JMenuItem();
        jmnReportClientes = new javax.swing.JMenu();
        jmnTransport = new javax.swing.JMenu();
        jmnkilometr = new javax.swing.JMenuItem();
        jmnhoraykilometr = new javax.swing.JMenuItem();
        jmnRecorrido = new javax.swing.JMenuItem();
        jmnReportContHotel = new javax.swing.JMenuItem();
        mnServiComple = new javax.swing.JMenuItem();
        mnTempHotel = new javax.swing.JMenuItem();
        mnPaquetTurist = new javax.swing.JMenuItem();
        jmenuAyuda = new javax.swing.JMenu();
        jmenuComentarios = new javax.swing.JMenuItem();
        jmenuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conozca Cuba");

        jMenu.setText("Menu");
        jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActionPerformed(evt);
            }
        });

        jmenuCerrarSeccion.setText("Cerrar Sección");
        jmenuCerrarSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCerrarSeccionActionPerformed(evt);
            }
        });
        jMenu.add(jmenuCerrarSeccion);

        jmnSalir.setText("Salir");
        jmnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnSalirActionPerformed(evt);
            }
        });
        jMenu.add(jmnSalir);

        jmnBarra.add(jMenu);

        jMenu1.setText("Ver");

        jmnHotelesActivos.setText("Hoteles Activos");
        jmnHotelesActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnHotelesActivosActionPerformed(evt);
            }
        });
        jMenu1.add(jmnHotelesActivos);

        mnPaquetCread.setText("Paquetes Creados");
        mnPaquetCread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPaquetCreadActionPerformed(evt);
            }
        });
        jMenu1.add(mnPaquetCread);

        jmnBarra.add(jMenu1);

        jmnReportClientes.setText("Reporter");
        jmnReportClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnReportClientesActionPerformed(evt);
            }
        });

        jmnTransport.setText("Transportes por");

        jmnkilometr.setText("Kilometraje");
        jmnkilometr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnkilometrActionPerformed(evt);
            }
        });
        jmnTransport.add(jmnkilometr);

        jmnhoraykilometr.setText("Horas y Kilometraje");
        jmnhoraykilometr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnhoraykilometrActionPerformed(evt);
            }
        });
        jmnTransport.add(jmnhoraykilometr);

        jmnRecorrido.setText("Recorridos");
        jmnRecorrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnRecorridoActionPerformed(evt);
            }
        });
        jmnTransport.add(jmnRecorrido);

        jmnReportClientes.add(jmnTransport);

        jmnReportContHotel.setText("Hoteles");
        jmnReportContHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnReportContHotelActionPerformed(evt);
            }
        });
        jmnReportClientes.add(jmnReportContHotel);

        mnServiComple.setText("Servicio complementario");
        mnServiComple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnServiCompleActionPerformed(evt);
            }
        });
        jmnReportClientes.add(mnServiComple);

        mnTempHotel.setText("Temporadas de Hoteles");
        mnTempHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTempHotelActionPerformed(evt);
            }
        });
        jmnReportClientes.add(mnTempHotel);

        mnPaquetTurist.setText("Ventas Paquetes Turisticos");
        mnPaquetTurist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPaquetTuristActionPerformed(evt);
            }
        });
        jmnReportClientes.add(mnPaquetTurist);

        jmnBarra.add(jmnReportClientes);

        jmenuAyuda.setText("Ayuda");

        jmenuComentarios.setText("Comentarios");
        jmenuComentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuComentariosActionPerformed(evt);
            }
        });
        jmenuAyuda.add(jmenuComentarios);

        jmenuSobre.setText("Sobre");
        jmenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuSobreActionPerformed(evt);
            }
        });
        jmenuAyuda.add(jmenuSobre);

        jmnBarra.add(jmenuAyuda);

        setJMenuBar(jmnBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuCerrarSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCerrarSeccionActionPerformed
        // TODO add your handling code here:
       VentanaInicial i = new VentanaInicial();
	   VentanaMenuAdmin.this.dispose();
	   i.setVisible(true);
	   
    }//GEN-LAST:event_jmenuCerrarSeccionActionPerformed

    private void jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActionPerformed
        // TODO add your handling code here:
		
    }//GEN-LAST:event_jMenuActionPerformed

    private void jmenuComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuComentariosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmenuComentariosActionPerformed

    private void jmenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuSobreActionPerformed
        // TODO add your handling code here:
		VentanaSobre s = new VentanaSobre();
		s.setVisible(true);
        
    }//GEN-LAST:event_jmenuSobreActionPerformed

    private void jmnReportContHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnReportContHotelActionPerformed
        // TODO add your handling code here:
        VentanaRepContConcHotel rh = new VentanaRepContConcHotel();
		rh.setVisible(true);
    }//GEN-LAST:event_jmnReportContHotelActionPerformed

    private void jmnkilometrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnkilometrActionPerformed
        // TODO add your handling code here:
        VentanaRepContCostK ck = new VentanaRepContCostK();
		ck.setVisible(true);
    }//GEN-LAST:event_jmnkilometrActionPerformed

    private void jmnhoraykilometrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnhoraykilometrActionPerformed
        // TODO add your handling code here:
        VentanaRepContCostHK chk = new VentanaRepContCostHK();
		chk.setVisible(true);
    }//GEN-LAST:event_jmnhoraykilometrActionPerformed

    private void jmnRecorridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnRecorridoActionPerformed
        // TODO add your handling code here:
        VentanaRepContRecorr cr = new VentanaRepContRecorr();
		cr.setVisible(true);
    }//GEN-LAST:event_jmnRecorridoActionPerformed

    private void jmnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnSalirActionPerformed
        // TODO add your handling code here:
		VentanaMenuAdmin.this.dispose();
    }//GEN-LAST:event_jmnSalirActionPerformed

    private void jmnHotelesActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnHotelesActivosActionPerformed
        // TODO add your handling code here:
		VentanaRepHotelesActivos ha = new VentanaRepHotelesActivos();
		ha.setVisible(true);
    }//GEN-LAST:event_jmnHotelesActivosActionPerformed

    private void mnServiCompleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnServiCompleActionPerformed
        // TODO add your handling code here:
		 VentanaRepContServComp sc = new VentanaRepContServComp();
		 sc.setVisible(true);
    }//GEN-LAST:event_mnServiCompleActionPerformed

    private void mnPaquetTuristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPaquetTuristActionPerformed
        // TODO add your handling code here:
		VentanaRepVentPQT pqt = new VentanaRepVentPQT();
		pqt.setVisible(true);
    }//GEN-LAST:event_mnPaquetTuristActionPerformed

    private void jmnReportClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnReportClientesActionPerformed
        // TODO add your handling code here:
		
    }//GEN-LAST:event_jmnReportClientesActionPerformed

    private void mnTempHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTempHotelActionPerformed
        // TODO add your handling code here:
		VentanaRepContTempHotel th = new VentanaRepContTempHotel();
		th.setVisible(true);
    }//GEN-LAST:event_mnTempHotelActionPerformed

    private void mnPaquetCreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPaquetCreadActionPerformed
        // TODO add your handling code here:
		VentanasRepPQTurist pt = new VentanasRepPQTurist();
		pt.setVisible(true);
    }//GEN-LAST:event_mnPaquetCreadActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(VentanaMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(VentanaMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(VentanaMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(VentanaMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new VentanaMenuAdmin().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jmenuAyuda;
    private javax.swing.JMenuItem jmenuCerrarSeccion;
    private javax.swing.JMenuItem jmenuComentarios;
    private javax.swing.JMenuItem jmenuSobre;
    private javax.swing.JMenuBar jmnBarra;
    private javax.swing.JMenuItem jmnHotelesActivos;
    private javax.swing.JMenuItem jmnRecorrido;
    private javax.swing.JMenu jmnReportClientes;
    private javax.swing.JMenuItem jmnReportContHotel;
    private javax.swing.JMenuItem jmnSalir;
    private javax.swing.JMenu jmnTransport;
    private javax.swing.JMenuItem jmnhoraykilometr;
    private javax.swing.JMenuItem jmnkilometr;
    private javax.swing.JMenuItem mnPaquetCread;
    private javax.swing.JMenuItem mnPaquetTurist;
    private javax.swing.JMenuItem mnServiComple;
    private javax.swing.JMenuItem mnTempHotel;
    // End of variables declaration//GEN-END:variables
}
