/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Interfaz.VentanaRepCli;
import Interfaz.VentanaRepContConcHotel;

import javax.swing.JPanel;

/**
 *
 * @author Rui Sergio Mané
 */
public class VentanaMenuTrabajador extends javax.swing.JFrame {
     
	/**
	 * Creates new form VentanaPrincipal
	 */
	public VentanaMenuTrabajador() {
		initComponents();
		
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jmnBarra = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        mnAbrir = new javax.swing.JMenuItem();
        mnCerrarSeccion = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenuItem();
        jmnVer = new javax.swing.JMenu();
        mnHotelesActivos = new javax.swing.JMenuItem();
        mnPaquetCread = new javax.swing.JMenuItem();
        mnReportes = new javax.swing.JMenu();
        mnReportTransp = new javax.swing.JMenu();
        mnHoraxKilo = new javax.swing.JMenuItem();
        mnKilo = new javax.swing.JMenuItem();
        mnRecorrido = new javax.swing.JMenuItem();
        mnAyuda = new javax.swing.JMenu();
        mnComentarios = new javax.swing.JMenuItem();
        mnSobre = new javax.swing.JMenuItem();

        jMenuItem9.setText("jMenuItem9");

        jMenuItem10.setText("jMenuItem10");

        jMenuItem11.setText("jMenuItem11");

        jMenuItem12.setText("jMenuItem12");

        jMenuItem15.setText("jMenuItem15");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conozca Cuba ");

        jMenu.setText("Menu");
        jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActionPerformed(evt);
            }
        });

        mnAbrir.setText("Abrir Paquete");
        mnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAbrirActionPerformed(evt);
            }
        });
        jMenu.add(mnAbrir);

        mnCerrarSeccion.setText("Cerrar Sección");
        mnCerrarSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCerrarSeccionActionPerformed(evt);
            }
        });
        jMenu.add(mnCerrarSeccion);

        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        jMenu.add(mnSalir);

        jmnBarra.add(jMenu);

        jmnVer.setText("Ver");

        mnHotelesActivos.setText("Hoteles Activos");
        mnHotelesActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnHotelesActivosActionPerformed(evt);
            }
        });
        jmnVer.add(mnHotelesActivos);

        mnPaquetCread.setText("Paquetes Creados");
        mnPaquetCread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPaquetCreadActionPerformed(evt);
            }
        });
        jmnVer.add(mnPaquetCread);

        jmnBarra.add(jmnVer);

        mnReportes.setText("Reportes");

        mnReportTransp.setText("Transporte por ");

        mnHoraxKilo.setText("Hora x kilometraje");
        mnHoraxKilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnHoraxKiloActionPerformed(evt);
            }
        });
        mnReportTransp.add(mnHoraxKilo);

        mnKilo.setText("Kilometraje");
        mnKilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKiloActionPerformed(evt);
            }
        });
        mnReportTransp.add(mnKilo);

        mnRecorrido.setText("Recorrido");
        mnRecorrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRecorridoActionPerformed(evt);
            }
        });
        mnReportTransp.add(mnRecorrido);

        mnReportes.add(mnReportTransp);

        jmnBarra.add(mnReportes);

        mnAyuda.setText("Ayuda");

        mnComentarios.setText("Comentarios");
        mnComentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnComentariosActionPerformed(evt);
            }
        });
        mnAyuda.add(mnComentarios);

        mnSobre.setText("Sobre");
        mnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSobreActionPerformed(evt);
            }
        });
        mnAyuda.add(mnSobre);

        jmnBarra.add(mnAyuda);

        setJMenuBar(jmnBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // 
	
	
    private void mnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSobreActionPerformed
        // TODO add your handling code here:
		VentanaSobre sobre = new VentanaSobre();
		sobre.setVisible(true);
    }//GEN-LAST:event_mnSobreActionPerformed

    private void mnComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnComentariosActionPerformed
        // TODO add your handling code here:
		VentanaComentarios ayuda = new VentanaComentarios();
		ayuda.setVisible(true);
    }//GEN-LAST:event_mnComentariosActionPerformed
        
		
    private void mnCerrarSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCerrarSeccionActionPerformed
        // TODO add your handling code here:
	    VentanaInicial i = new VentanaInicial();	
		i.setVisible(true);
		VentanaMenuTrabajador.this.setVisible(false);
    }//GEN-LAST:event_mnCerrarSeccionActionPerformed

    private void jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActionPerformed
		// TODO add your handling code here:
			
    }//GEN-LAST:event_jMenuActionPerformed

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        // TODO add your handling code here:
		VentanaMenuTrabajador.this.dispose();
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mnHotelesActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnHotelesActivosActionPerformed
        // TODO add your handling code here:
        VentanaRepHotelesActivos ha = new VentanaRepHotelesActivos();
		ha.setVisible(true);
    }//GEN-LAST:event_mnHotelesActivosActionPerformed

    private void mnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAbrirActionPerformed
        // TODO add your handling code here:
		VentanaAbrirPaquete ap = new VentanaAbrirPaquete();
		ap.setVisible(true);
    }//GEN-LAST:event_mnAbrirActionPerformed

    private void mnKiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKiloActionPerformed
        // TODO add your handling code here:
		VentanaRepContCostK k = new VentanaRepContCostK();
		k.setVisible(true);
    }//GEN-LAST:event_mnKiloActionPerformed

    private void mnHoraxKiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnHoraxKiloActionPerformed
        // TODO add your handling code here:
		VentanaRepContCostHK hk = new VentanaRepContCostHK();
		hk.setVisible(true);
    }//GEN-LAST:event_mnHoraxKiloActionPerformed

    private void mnRecorridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRecorridoActionPerformed
        // TODO add your handling code here:
		VentanaRepContRecorr r = new VentanaRepContRecorr();
		r.setVisible(true);
    }//GEN-LAST:event_mnRecorridoActionPerformed

    private void mnPaquetCreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPaquetCreadActionPerformed
        // TODO add your handling code here:
		VentanasRepPQTurist pt = new VentanasRepPQTurist();
		pt.setVisible(true);
    }//GEN-LAST:event_mnPaquetCreadActionPerformed

	/**
	 * @param args the command line arguments
	 */
	
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(VentanaMenuTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(VentanaMenuTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(VentanaMenuTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(VentanaMenuTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new VentanaMenuTrabajador().setVisible(true);
			}
		});
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuBar jmnBarra;
    private javax.swing.JMenu jmnVer;
    private javax.swing.JMenuItem mnAbrir;
    private javax.swing.JMenu mnAyuda;
    private javax.swing.JMenuItem mnCerrarSeccion;
    private javax.swing.JMenuItem mnComentarios;
    private javax.swing.JMenuItem mnHoraxKilo;
    private javax.swing.JMenuItem mnHotelesActivos;
    private javax.swing.JMenuItem mnKilo;
    private javax.swing.JMenuItem mnPaquetCread;
    private javax.swing.JMenuItem mnRecorrido;
    private javax.swing.JMenu mnReportTransp;
    private javax.swing.JMenu mnReportes;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JMenuItem mnSobre;
    // End of variables declaration//GEN-END:variables
}
